import React from "react";
import { motion } from "framer-motion";
import AwardCard from "../../components/AwardCard/AwardCard";
import "./Awards.css";

export default function Awards() {
  const awards = [
    {
      id: 1,
      title: "Benevolent",
      recipient: "Vaibhav Karan",
      description: "",
      tier: "gold",
    },
    {
      id: 2,
      title: "Rotivore",
      recipient: "Ahaan Rastogi",
      description: "",
      tier: "gold",
    },
    {
      id: 3,
      title: "BathroomVIP",
      recipient: "Pradhyumna Guttula",
      description: "",
      tier: "gold",
    },
    {
      id: 4,
      title: "ShakespeareReborn",
      recipient: "Voleti Sakshi",
      description: "",
      tier: "gold",
    },
    {
      id: 5,
      title: "",
      recipient: "Sreenika Akoju",
      description: "",
      tier: "gold",
    },
    {
      id: 6,
      title: "",
      recipient: "Chaitra Mudiyala",
      description: "",
      tier: "gold",
    },
    {
      id: 7,
      title: "Dostana",
      recipient: "Kancharla Ram Kiran Reddy",
      description: "",
      tier: "gold",
    },
    {
      id: 8,
      title: "",
      recipient: "Nikhil Kintali",
      description: "",
      tier: "gold",
    },
    {
      id: 9,
      title: "OfficialBaby",
      recipient: "Praneel Reddy Ambati",
      description: "",
      tier: "gold",
    },
    {
      id: 10,
      title: "SneezeAlarm",
      recipient: "Vrushank Molkar",
      description: "",
      tier: "gold",
    },
    {
      id: 11,
      title: "BuiltInBestie",
      recipient: "Rida Imam",
      description: "",
      tier: "gold",
    },
    {
      id: 12,
      title: "Kerlite",
      recipient: "Arjun Anumolu",
      description: "",
      tier: "gold",
    },
    {
      id: 13,
      title: "",
      recipient: "Srihan Gondlyala",
      description: "",
      tier: "gold",
    },
    {
      id: 14,
      title: "Happy virus",
      recipient: "Soorya Bhubesh",
      description: "",
      tier: "gold",
    },
    {
      id: 15,
      title: "Smurf,submarine",
      recipient: "Hemakesh Byna",
      description: "",
      tier: "gold",
    },
    {
      id: 16,
      title: "Mallu",
      recipient: "Eva Ajith",
      description: "",
      tier: "gold",
    },
    {
      id: 17,
      title: "",
      recipient: "Phani Devi Sri Lakshmi Godavarthy",
      description: "",
      tier: "gold",
    },
    {
      id: 18,
      title: "",
      recipient: "Sai Siva Sreeram Godavarthy",
      description: "",
      tier: "gold",
    },
    {
      id: 19,
      title: "Miss sunshine",
      recipient: "Vigneswari Teppala",
      description: "",
      tier: "gold",
    },
    {
      id: 20,
      title: "Assignment Accepted",
      recipient: "Harshith Cheryala",
      description: "",
      tier: "gold",
    },
    {
      id: 21,
      title: "Mr.Cool",
      recipient: "Indraneel Sangle",
      description: "",
      tier: "gold",
    },
    {
      id: 22,
      title: "Study Machine",
      recipient: "R Sai Harshil",
      description: "",
      tier: "gold",
    },
    {
      id: 23,
      title: "Dead line destroyer",
      recipient: "Stuti Talasila",
      description: "",
      tier: "gold",
    },
    {
      id: 24,
      title: "Born To Win",
      recipient: "Lokesh Charan Jonnaganti",
      description: "",
      tier: "gold",
    },
    {
      id: 25,
      title: "Prompt And Perfect",
      recipient: "Pranav Krishna Kollimarla",
      description: "",
      tier: "gold",
    },
    {
      id: 26,
      title: "Messy Hair Dont Care",
      recipient: "Aditya Pranav Marrapu",
      description: "",
      tier: "gold",
    },
    {
      id: 27,
      title: "Everything Needs Analysis",
      recipient: "Saee Kiran Kalambhar",
      description: "",
      tier: "gold",
    },
    {
      id: 28,
      title: "Living On Vibes",
      recipient: "Chaturya Hrishikesh Reddy Avula",
      description: "",
      tier: "gold",
    },
    {
      id: 29,
      title: "Speech With Spice",
      recipient: "Prajith Suhaas Mukkamala",
      description: "",
      tier: "silver",
    },
    {
      id: 30,
      title: "Miss sunshine",
      recipient: "J K Samyuktha",
      description: "",
      tier: "silver",
    },
    {
      id: 31,
      title: "yawn specialist",
      recipient: "Indhu Sahasra Mandapati",
      description: "",
      tier: "silver",
    },
    {
      id: 32,
      title: "walking wikipedia",
      recipient: "Jayant Panidarapu",
      description: "",
      tier: "silver",
    },
    {
      id: 33,
      title: "Academic Weapon",
      recipient: "Om",
      description: "",
      tier: "silver",
    },
    {
      id: 34,
      title: "Etiquette Expert",
      recipient: "Tanish Gorli",
      description: "",
      tier: "silver",
    },
    {
      id: 35,
      title: "Font Factory",
      recipient: "Govarna P Pentakota",
      description: "",
      tier: "silver",
    },
    {
      id: 36,
      title: "Hindi Teacher Ka Right Hand",
      recipient: "Sai Saharsh Neetoori",
      description: "",
      tier: "silver",
    },
    {
      id: 37,
      title: "",
      recipient: "Advait Dubey",
      description: "",
      tier: "silver",
    },
    {
      id: 38,
      title: "late submission pro",
      recipient: "Gayam Jeevan Ashik Reddy",
      description: "",
      tier: "silver",
    },
    {
      id: 39,
      title: "Try hard",
      recipient: "Lorish Bagh",
      description: "",
      tier: "silver",
    },
    {
      id: 40,
      title: "",
      recipient: "Veda Varshit Medikonduri",
      description: "",
      tier: "silver",
    },
    {
      id: 41,
      title: "Dog Ate My Homework Level",
      recipient: "Rajdeep Bhattacharjee",
      description: "",
      tier: "silver",
    },
    {
      id: 42,
      title: "Tiny champ",
      recipient: "Jangita Hasini",
      description: "",
      tier: "silver",
    },
    {
      id: 43,
      title: "#World Revolves Around Me",
      recipient: "B Shravan",
      description: "",
      tier: "silver",
    },
    {
      id: 44,
      title: "Too Happy For No Reason",
      recipient: "Chavali Kiran Kumar",
      description: "",
      tier: "silver",
    },
    {
      id: 45,
      title: "",
      recipient: "Anagh Goka",
      description: "",
      tier: "silver",
    },
    {
      id: 46,
      title: "Beauty Over Everything",
      recipient: "Akula Rakshitha",
      description: "",
      tier: "silver",
    },
    {
      id: 47,
      title: "Born For Exams (sarcasm)",
      recipient: "S Saathwik",
      description: "",
      tier: "silver",
    },
    {
      id: 48,
      title: "",
      recipient: "Vanij Sri Krishna Kathi",
      description: "",
      tier: "silver",
    },
    {
      id: 49,
      title: "Angry bird",
      recipient: "Subhankar Mahapatra",
      description: "",
      tier: "silver",
    },
    {
      id: 50,
      title: "",
      recipient: "Nitya Santoshini Potluri",
      description: "",
      tier: "silver",
    },
    {
      id: 51,
      title: "",
      recipient: "Shyam Katta",
      description: "",
      tier: "silver",
    },
    {
      id: 52,
      title: "",
      recipient: "Chikkala Sravan Bhargav",
      description: "",
      tier: "silver",
    },
    {
      id: 53,
      title: "",
      recipient: "Vinnakota Anshul Maurya",
      description: "",
      tier: "silver",
    },
    {
      id: 54,
      title: "",
      recipient: "Vaishnavi Akkishetty",
      description: "",
      tier: "silver",
    },
    {
      id: 55,
      title: "",
      recipient: "Charith Jangam",
      description: "",
      tier: "silver",
    },
    {
      id: 56,
      title: "",
      recipient: "Konumuri Bhavya Sree Swetcha",
      description: "",
      tier: "bronze",
    },
    {
      id: 57,
      title: "Part Time Student",
      recipient: "C H Jai Ashish Chadalavada",
      description: "",
      tier: "bronze",
    },
    {
      id: 58,
      title: "",
      recipient: "Adhiraj B",
      description: "",
      tier: "bronze",
    },
    {
      id: 59,
      title: "",
      recipient: "Saketh V",
      description: "",
      tier: "bronze",
    },
    {
      id: 60,
      title: "",
      recipient: "Sohan SVS",
      description: "",
      tier: "bronze",
    },
    {
      id: 61,
      title: "Net Breaker",
      recipient: "Ruthwik Krishna Thummanapelli",
      description: "",
      tier: "bronze",
    },
    {
      id: 62,
      title: "",
      recipient: "Sree Vardhan Mukka",
      description: "",
      tier: "bronze",
    },
    {
      id: 63,
      title: "",
      recipient: "Mishfa Zainab",
      description: "",
      tier: "bronze",
    },
    {
      id: 64,
      title: "",
      recipient: "Maanvitha Sri Veerapaneni",
      description: "",
      tier: "bronze",
    },
    {
      id: 65,
      title: "",
      recipient: "Sasanth Reddy Athipalli",
      description: "",
      tier: "bronze",
    },
    {
      id: 66,
      title: "",
      recipient: "Yepuri Jessica Joy",
      description: "",
      tier: "bronze",
    },
    {
      id: 67,
      title: "",
      recipient: "Sri Lasya Muppavapu",
      description: "",
      tier: "bronze",
    },
    {
      id: 68,
      title: "",
      recipient: "Dabbani Aditya",
      description: "",
      tier: "bronze",
    },
    {
      id: 69,
      title: "",
      recipient: "Farhan Khan",
      description: "",
      tier: "bronze",
    },
    {
      id: 70,
      title: "",
      recipient: "Sindhuja Chalamalasetty",
      description: "",
      tier: "bronze",
    },
    {
      id: 71,
      title: "",
      recipient: "Sri Sahasra",
      description: "",
      tier: "bronze",
    },
    {
      id: 72,
      title: "",
      recipient: "Moukthika P",
      description: "",
      tier: "bronze",
    },
    {
      id: 73,
      title: "",
      recipient: "Thenebanda Snehita",
      description: "",
      tier: "bronze",
    },
    {
      id: 74,
      title: "",
      recipient: "Mohana Murali Mandava",
      description: "",
      tier: "bronze",
    },
    {
      id: 75,
      title: "",
      recipient: "Yerukonda Pramath Sri Krishna",
      description: "",
      tier: "bronze",
    },
    {
      id: 76,
      title: "",
      recipient: "Palempalli Grahitha Reddy",
      description: "",
      tier: "bronze",
    },
    {
      id: 77,
      title: "",
      recipient: "Vedith Vamshi Krishna Yanna",
      description: "",
      tier: "bronze",
    },
    {
      id: 78,
      title: "",
      recipient: "Harsh Gandra",
      description: "",
      tier: "bronze",
    },
    {
      id: 79,
      title: "",
      recipient: "Shaik Irfan",
      description: "",
      tier: "bronze",
    },
    {
      id: 80,
      title: "",
      recipient: "Samyak NH",
      description: "",
      tier: "bronze",
    },
    {
      id: 81,
      title: "",
      recipient: "Laasya Siri Jujjavarapu",
      description: "",
      tier: "bronze",
    },
    {
      id: 82,
      title: "",
      recipient: "Lakshmi Sahasra M",
      description: "",
      tier: "bronze",
    },
    {
      id: 83,
      title: "",
      recipient: "Amuktha Jalapu",
      description: "",
      tier: "bronze",
    },
  ];

  return (
    <motion.div
      className="awards-page"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.8 }}
    >
      <div className="awards-header">
        <h1 className="section-title">Fun Taglines</h1>
        <p className="section-subtitle">
          Creative nicknames given by teachers
        </p>
      </div>

      <div className="awards-grid">
        {awards.map((award, index) => (
          <AwardCard key={award.id} award={award} index={index} />
        ))}
      </div>
    </motion.div>
  );
}